### ISSUE TITLE
database

### ISSUE THREAD

**Issue by serhatunur** [suleymangunes/online_education_app_with_backend_and_mockup#1]
firebase kullanmısısınız suan o database nasıl ulaşabiliriz uygulamayı çalıştırmak için database ihtiyacım var

**Comment by suleymangunes** [comment]
Firebase projesi oluştururak 2 ayrı collection olusturmalısın. İlki Person collectionu. İcerisinde field olarak email, password ve userName degerlerini alır. Ayrıca içerisinde alinacakdersler collectionu bulunur. Bu collection icerisinde ders degerine karsilik id degeri bulundurur. Bu id degeri de ikinci collectionumuz dersler colecction icerisindeki document id değerlerine karşılık gelir. Bu collection da field olarak dersadi, dersalindimi, dersicerigi, ogretmenid, ogretmenisim ve canliid degerlerini bulundurur. Firebase hesabınızda kolayca oluşturabilirsiniz. Ayrıca Authentication işlemleri için gerekli extensionu da eklemeyi unutmayın.
